name: ci
on:
  push: { branches: ["**"] }
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v4
      - &setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - &cache
        name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - &upgrade-pip
        run: python -m pip install -U pip
      - &install-deps
        run: pip install -e .[dev]
      - run: ruff check .

  type:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-python
      - *cache
      - *upgrade-pip
      - *install-deps
      - run: mypy src

  test:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-python
      - *cache
      - *upgrade-pip
      - *install-deps
      - run: pytest -q
